### ISSUE TITLE
watchOS App

### ISSUE THREAD

**Issue by ndPPPhz** [sirslab/COVID-19-DoNTYF-wear#7]
Hello,
after watching the prototype at the following URL:
https://sites.google.com/unisi.it/noface-touchapp/ 
I have decided to contribute creating a new branch for starting the development of the watchOS ( AppleWatch ).

Since there are no documentation/flow of the current prototype for Android and I don't have the permission in order to create a branch, could you sort them out for me?

**Comment by Gianpaolocci** [comment]
Hi,
Thanks for asking, we really appreciate your help! 
I added the app flow we defined for the Android App in the Read_me file, so that is easier to understand how the app works. We can create an ad-hoc branch called "SmartOS_app" so that you can fork it and the request pulls. If you want to contact us directly, please write at sirslabsiena@gmail.com.
